/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BetChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE"
      | "createBet"
      | "finalizeBet"
      | "getAllBets"
      | "getBetFullInfo"
      | "getBetOptions"
      | "getTotalBets"
      | "getUserBetAmount"
      | "nextId"
      | "placeBet"
      | "withdrawFee"
      | "withdrawPrize"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetCreated"
      | "BetFinalized"
      | "BetPlaced"
      | "FeeWithdrawn"
      | "PrizeWithdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createBet",
    values: [string, string, string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllBets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBetFullInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBetOptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBetAmount",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPrize",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "FEE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBetFullInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBetOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPrize",
    data: BytesLike
  ): Result;
}

export namespace BetCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    title: string,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    title: string,
    deadline: bigint
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    title: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetFinalizedEvent {
  export type InputTuple = [id: BigNumberish, winningOption: BigNumberish];
  export type OutputTuple = [id: bigint, winningOption: bigint];
  export interface OutputObject {
    id: bigint;
    winningOption: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    id: BigNumberish,
    optionId: BigNumberish,
    bettor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    optionId: bigint,
    bettor: string,
    amount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    optionId: bigint;
    bettor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeWithdrawnEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, creator: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizeWithdrawnEvent {
  export type InputTuple = [
    id: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, winner: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BetChain extends BaseContract {
  connect(runner?: ContractRunner | null): BetChain;
  waitForDeployment(): Promise<this>;

  interface: BetChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE: TypedContractMethod<[], [bigint], "view">;

  createBet: TypedContractMethod<
    [
      title: string,
      description: string,
      imageUrl: string,
      optionNames: string[],
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  finalizeBet: TypedContractMethod<
    [betId: BigNumberish, winningOptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllBets: TypedContractMethod<
    [start: BigNumberish, count: BigNumberish],
    [
      [
        bigint[],
        string[],
        string[],
        string[],
        bigint[],
        boolean[],
        boolean[],
        bigint[],
        bigint[]
      ] & {
        ids: bigint[];
        creators: string[];
        titles: string[];
        imageUrls: string[];
        pools: bigint[];
        actives: boolean[];
        finals: boolean[];
        optionsCounts: bigint[];
        deadlines: bigint[];
      }
    ],
    "view"
  >;

  getBetFullInfo: TypedContractMethod<
    [betId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        title: string;
        description: string;
        imageUrl: string;
        totalPool: bigint;
        active: boolean;
        finalized: boolean;
        optionsCount: bigint;
        deadline: bigint;
        winningOption: bigint;
      }
    ],
    "view"
  >;

  getBetOptions: TypedContractMethod<
    [betId: BigNumberish],
    [[string[], bigint[]] & { names: string[]; totals: bigint[] }],
    "view"
  >;

  getTotalBets: TypedContractMethod<[], [bigint], "view">;

  getUserBetAmount: TypedContractMethod<
    [betId: BigNumberish, optionId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  nextId: TypedContractMethod<[], [bigint], "view">;

  placeBet: TypedContractMethod<
    [betId: BigNumberish, optionId: BigNumberish],
    [void],
    "payable"
  >;

  withdrawFee: TypedContractMethod<[betId: BigNumberish], [void], "nonpayable">;

  withdrawPrize: TypedContractMethod<
    [betId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createBet"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      imageUrl: string,
      optionNames: string[],
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeBet"
  ): TypedContractMethod<
    [betId: BigNumberish, winningOptionId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllBets"
  ): TypedContractMethod<
    [start: BigNumberish, count: BigNumberish],
    [
      [
        bigint[],
        string[],
        string[],
        string[],
        bigint[],
        boolean[],
        boolean[],
        bigint[],
        bigint[]
      ] & {
        ids: bigint[];
        creators: string[];
        titles: string[];
        imageUrls: string[];
        pools: bigint[];
        actives: boolean[];
        finals: boolean[];
        optionsCounts: bigint[];
        deadlines: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBetFullInfo"
  ): TypedContractMethod<
    [betId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        title: string;
        description: string;
        imageUrl: string;
        totalPool: bigint;
        active: boolean;
        finalized: boolean;
        optionsCount: bigint;
        deadline: bigint;
        winningOption: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBetOptions"
  ): TypedContractMethod<
    [betId: BigNumberish],
    [[string[], bigint[]] & { names: string[]; totals: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalBets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBetAmount"
  ): TypedContractMethod<
    [betId: BigNumberish, optionId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [betId: BigNumberish, optionId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawFee"
  ): TypedContractMethod<[betId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPrize"
  ): TypedContractMethod<[betId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BetCreated"
  ): TypedContractEvent<
    BetCreatedEvent.InputTuple,
    BetCreatedEvent.OutputTuple,
    BetCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BetFinalized"
  ): TypedContractEvent<
    BetFinalizedEvent.InputTuple,
    BetFinalizedEvent.OutputTuple,
    BetFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "FeeWithdrawn"
  ): TypedContractEvent<
    FeeWithdrawnEvent.InputTuple,
    FeeWithdrawnEvent.OutputTuple,
    FeeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "PrizeWithdrawn"
  ): TypedContractEvent<
    PrizeWithdrawnEvent.InputTuple,
    PrizeWithdrawnEvent.OutputTuple,
    PrizeWithdrawnEvent.OutputObject
  >;

  filters: {
    "BetCreated(uint256,address,string,uint256)": TypedContractEvent<
      BetCreatedEvent.InputTuple,
      BetCreatedEvent.OutputTuple,
      BetCreatedEvent.OutputObject
    >;
    BetCreated: TypedContractEvent<
      BetCreatedEvent.InputTuple,
      BetCreatedEvent.OutputTuple,
      BetCreatedEvent.OutputObject
    >;

    "BetFinalized(uint256,uint256)": TypedContractEvent<
      BetFinalizedEvent.InputTuple,
      BetFinalizedEvent.OutputTuple,
      BetFinalizedEvent.OutputObject
    >;
    BetFinalized: TypedContractEvent<
      BetFinalizedEvent.InputTuple,
      BetFinalizedEvent.OutputTuple,
      BetFinalizedEvent.OutputObject
    >;

    "BetPlaced(uint256,uint256,address,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "FeeWithdrawn(uint256,address,uint256)": TypedContractEvent<
      FeeWithdrawnEvent.InputTuple,
      FeeWithdrawnEvent.OutputTuple,
      FeeWithdrawnEvent.OutputObject
    >;
    FeeWithdrawn: TypedContractEvent<
      FeeWithdrawnEvent.InputTuple,
      FeeWithdrawnEvent.OutputTuple,
      FeeWithdrawnEvent.OutputObject
    >;

    "PrizeWithdrawn(uint256,address,uint256)": TypedContractEvent<
      PrizeWithdrawnEvent.InputTuple,
      PrizeWithdrawnEvent.OutputTuple,
      PrizeWithdrawnEvent.OutputObject
    >;
    PrizeWithdrawn: TypedContractEvent<
      PrizeWithdrawnEvent.InputTuple,
      PrizeWithdrawnEvent.OutputTuple,
      PrizeWithdrawnEvent.OutputObject
    >;
  };
}
